### ISSUE TITLE
Temperature creeps up and print stops

### ISSUE THREAD

**Issue by stemaDev** [KevinOConnor/klipper#1185]
I have an ender 3 with an mks gen 1.4 board (v6 hotend, but stock heater and thermistor). I set up everything, but when printing the calibration cube from petg @ 250°C, after 8-10 minutes the temperature starts to creep up and at one point it reaches 265 (which I set as max_temp) and it shuts down. When it tries to cool below the target temp, it immediately jumps over the previously reached highest temp. I already have 12 failed cubes.
I made a successful print @ 240°C, but after that 8-10 minutes it started to fluctuate even went to almost 253°C at one point (3rd picture)
I thought of thermistor (which I already replaced, but things didn't improve) and heater issues, but I didn't have problems with marlin. Also if the temperature would go down, it would make sense that some hardware's not working, but it's going up, so my best guess is the firmware. Something needs to give it power to heat, and also the temperature readings are there, I'm seeing the same readings as what the firmware.
I really like klipper, and would like to continue using it. Hopefully we can figure it out. Thanks :)

LOG: [klippy.log](https://github.com/KevinOConnor/klipper/files/2824197/klippy.log)

Fail @ 250°C
![image](https://user-images.githubusercontent.com/43641170/52161810-3c190500-26cb-11e9-9414-f9a43bbbb43b.png)

![image](https://user-images.githubusercontent.com/43641170/52161814-4e933e80-26cb-11e9-8926-78b677c7c316.png)

Success with fluctiations @ 240°C
![image](https://user-images.githubusercontent.com/43641170/52162849-f57ed700-26d9-11e9-8169-0cc910fe744c.png)

**Comment by stemaDev** [comment]
Yes, several times, also tried with default and values from someone else with a similar setup

**Comment by DanielJoyce** [comment]
I've seen this octoprint, which is why in the past I stopped using and went to other software.

**Comment by stemaDev** [comment]
For me it might have been the board. Klipper was able to keep it close to the target for 5-10 minutes, but then it started to fluctuate and rise. I went back to marlin and though it was able to keep it around target, but was fluctuating near it with quite a few degrees. I changed thermistor, heater, but now I changed the board(was mks gen 1.4, now fysetc f6) and in marlin the temperature is super stable. I will try klipper if I have everything set up.

**Comment by MarcinKnD** [comment]
My problem is solved.
the problem was in the failure of the extruder heater. it worked until the cooling fan of the printout turned on. The heater did not have the power to keep the temperature, it just wore out. Exchange for a new solution to the problem. Now the extruder is holding the temperature.

**Comment by KevinOConnor** [comment]
@stemaDev - it looks like your extruder thermistor is very noisy - the raw temperatures are jumping around +-20 degrees.  That is causing the PID to not function correctly.  I'd double check your thermistor wiring to ensure it is not crimped or obstructed.

-Kevin

**Comment by stemaDev** [comment]
Maybe it's the board, I'm not sure, but I changed it now, don't know about klipper yet, if I'll still have issues with the new one, I'll reopen the ticket. Thank you!
